version: '3.9'


services:
  db:
    image: postgres:latest 
    restart: always
    container_name: Sinergia
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ../postgres_data:/var/lib/postgresql/data  # Corregido el destino del volumen

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL= ${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD= ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - 5050:80